// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// echo //
// ---- //

#define echo_wrap_target 0
#define echo_wrap 2
#define echo_pio_version 0

static const uint16_t echo_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xa0c7, //  1: mov    isr, osr                   
    0x8020, //  2: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program echo_program = {
    .instructions = echo_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config echo_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + echo_wrap_target, offset + echo_wrap);
    return c;
}
#endif
