// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// genseq //
// ------ //

#define genseq_wrap_target 0
#define genseq_wrap 4

static const uint16_t genseq_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0xa027, //  1: mov    x, osr          side 0     
    0xa0c1, //  2: mov    isr, x          side 0     
    0x9020, //  3: push   block           side 1     
    0x0042, //  4: jmp    x--, 2          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program genseq_program = {
    .instructions = genseq_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config genseq_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + genseq_wrap_target, offset + genseq_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

